name: Vixio
description: Vixio, The Discord addon created to meet all of your Discord needs.
main: me.iblitzkriegi.vixio.Vixio
version: @VERSION@
author: Blitz, Pikachu, Tuke_Nuke
website: http://vixio.space
depend: [Skript]
