name: Vixio
description: Vixio, The Discord addon created to meet all of your Discord needs.
main: me.iblitzkriegi.vixio.Vixio
version: 2.0.0-pre2
author: iBlitzkriegi, sky_high (Pikachu)
website: http://vixio.space
depend: [Skript]
commands:
  vixio:
    description: Default command for Vixio
    usage: /<command>
